
import { Theme } from './theme-types';

export const themes: Theme[] = [
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Sophisticated dark theme with electric blue accents',
    background: 'linear-gradient(135deg, #0c0c0f 0%, #1a1625 50%, #2d1b69 100%)',
    accentColor: '#00d4ff',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", "Inter", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(255, 255, 255, 0.08) 0%, rgba(255, 255, 255, 0.03) 100%)',
    isDark: true,
    categories: ['dark', 'modern', 'consulting']
  },
  {
    id: 'pristine',
    name: 'Pristine',
    description: 'Ultra-clean design with perfect contrast and spacing',
    background: '#ffffff',
    accentColor: '#2563eb',
    textColor: '#0f172a',
    titleFont: '"Inter", "SF Pro Display", sans-serif',
    bodyFont: '"Inter", "SF Pro Text", sans-serif',
    cardDesign: 'linear-gradient(145deg, #f8fafc 0%, #f1f5f9 100%)',
    isDark: false,
    categories: ['consulting', 'academic', 'modern']
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Deep black with warm amber highlights',
    background: 'linear-gradient(135deg, #000000 0%, #1c1c1c 50%, #2a2a2a 100%)',
    accentColor: '#f59e0b',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0.02) 100%)',
    isDark: true,
    categories: ['dark', 'consulting', 'modern']
  },
  {
    id: 'pearl',
    name: 'Pearl',
    description: 'Soft pearl finish with subtle blue undertones',
    background: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 50%, #e2e8f0 100%)',
    accentColor: '#3b82f6',
    textColor: '#1e293b',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.7)',
    isDark: false,
    categories: ['consulting', 'academic']
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Rich emerald with natural warmth',
    background: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    accentColor: '#10b981',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(16, 185, 129, 0.1) 0%, rgba(16, 185, 129, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'crimson',
    name: 'Crimson',
    description: 'Bold crimson gradients for impactful presentations',
    background: 'linear-gradient(135deg, #7f1d1d 0%, #991b1b 50%, #dc2626 100%)',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'sage',
    name: 'Sage',
    description: 'Calming sage green with premium typography',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #ecfdf5 50%, #f7fee7 100%)',
    accentColor: '#059669',
    textColor: '#374151',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.8)',
    isDark: false,
    categories: ['academic', 'consulting']
  },
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Deep navy with electric purple accents',
    background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)',
    accentColor: '#8b5cf6',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(139, 92, 246, 0.1) 0%, rgba(139, 92, 246, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern', 'consulting']
  },
  {
    id: 'platinum',
    name: 'Platinum',
    description: 'Premium metallic finish with sophisticated styling',
    background: 'linear-gradient(135deg, #f9fafb 0%, #f3f4f6 50%, #e5e7eb 100%)',
    accentColor: '#6366f1',
    textColor: '#111827',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'linear-gradient(145deg, #ffffff 0%, #f9fafb 100%)',
    isDark: false,
    categories: ['consulting', 'modern']
  },
  {
    id: 'copper',
    name: 'Copper',
    description: 'Warm copper tones with luxurious depth',
    background: 'linear-gradient(135deg, #451a03 0%, #7c2d12 50%, #ea580c 100%)',
    accentColor: '#fbbf24',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(251, 191, 36, 0.1) 0%, rgba(251, 191, 36, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'arctic',
    name: 'Arctic',
    description: 'Cool arctic blues with pristine clarity',
    background: 'linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 50%, #bae6fd 100%)',
    accentColor: '#0284c7',
    textColor: '#0c4a6e',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.7)',
    isDark: false,
    categories: ['academic', 'modern']
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    description: 'Deep space black with stellar highlights',
    background: 'linear-gradient(135deg, #000000 0%, #1a1a2e 50%, #16213e 100%)',
    accentColor: '#06b6d4',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(6, 182, 212, 0.1) 0%, rgba(6, 182, 212, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'ivory',
    name: 'Ivory',
    description: 'Warm ivory with elegant gold accents',
    background: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 50%, #fde68a 100%)',
    accentColor: '#d97706',
    textColor: '#92400e',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.8)',
    isDark: false,
    categories: ['academic', 'consulting']
  },
  {
    id: 'carbon',
    name: 'Carbon',
    description: 'Industrial carbon fiber with neon green highlights',
    background: 'linear-gradient(135deg, #1f2937 0%, #374151 50%, #4b5563 100%)',
    accentColor: '#22c55e',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(34, 197, 94, 0.1) 0%, rgba(34, 197, 94, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Soft lavender gradients with refined elegance',
    background: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 50%, #e9d5ff 100%)',
    accentColor: '#7c3aed',
    textColor: '#581c87',
    titleFont: '"SF Pro Display", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.7)',
    isDark: false,
    categories: ['academic', 'modern']
  }
  // ── EDUCATOR COLLECTION ──────────────────────────────────────────────────────
  {
    id: 'nova',
    name: 'Nova',
    description: 'Deep navy with electric blue — perfect for research & lectures',
    background: '#0d1b2a',
    accentColor: '#378ADD',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", "Inter", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", "Inter", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(55, 138, 221, 0.12) 0%, rgba(55, 138, 221, 0.04) 100%)',
    isDark: true,
    categories: ['dark', 'academic', 'educator']
  },
  {
    id: 'ivory-clean',
    name: 'Ivory',
    description: 'Clean white with purple rule — classic academic style',
    background: '#fdfaf5',
    accentColor: '#7c3aed',
    textColor: '#1a1a1a',
    titleFont: '"Inter", "SF Pro Display", sans-serif',
    bodyFont: '"Inter", "SF Pro Text", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.95)',
    isDark: false,
    categories: ['academic', 'educator', 'consulting']
  },
  {
    id: 'obsidian-editorial',
    name: 'Obsidian',
    description: 'Pure black editorial — bold headlines, stat-forward slides',
    background: '#111111',
    accentColor: '#a78bfa',
    textColor: '#ffffff',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(167, 139, 250, 0.08) 0%, rgba(167, 139, 250, 0.03) 100%)',
    isDark: true,
    categories: ['dark', 'modern', 'educator']
  },
  {
    id: 'aurora-edu',
    name: 'Aurora',
    description: 'Warm purple gradient — concept teaching & card layouts',
    background: 'linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)',
    accentColor: '#7c3aed',
    textColor: '#1e1b4b',
    titleFont: '"Inter", "SF Pro Display", sans-serif',
    bodyFont: '"Inter", "SF Pro Text", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.75)',
    isDark: false,
    categories: ['academic', 'educator', 'modern']
  },
  {
    id: 'sage-deep',
    name: 'Sage',
    description: 'Deep forest green — science, sustainability & STEM topics',
    background: '#0f2318',
    accentColor: '#6ee7b7',
    textColor: '#ecfdf5',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'linear-gradient(145deg, rgba(110, 231, 183, 0.1) 0%, rgba(110, 231, 183, 0.04) 100%)',
    isDark: true,
    categories: ['dark', 'academic', 'educator']
  },
  {
    id: 'slate',
    name: 'Slate',
    description: 'Clean neutral — large stats, evidence-based content',
    background: '#f8f9fa',
    accentColor: '#7c3aed',
    textColor: '#111827',
    titleFont: '"Inter", "SF Pro Display", sans-serif',
    bodyFont: '"Inter", "SF Pro Text", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 1)',
    isDark: false,
    categories: ['academic', 'educator', 'consulting', 'modern']
  },
  {
    id: 'crimson-band',
    name: 'Crimson',
    description: 'Bold red header band — business, metrics & consulting decks',
    background: '#ffffff',
    accentColor: '#991b1b',
    textColor: '#111827',
    titleFont: '"SF Pro Display", "Segoe UI", sans-serif',
    bodyFont: '"SF Pro Text", "Segoe UI", sans-serif',
    cardDesign: 'rgba(248, 248, 248, 1)',
    isDark: false,
    categories: ['consulting', 'modern', 'educator']
  },
  {
    id: 'pebble',
    name: 'Pebble',
    description: 'Warm cream with gold accents — quotes & introductory slides',
    background: '#f5f0e8',
    accentColor: '#d4a847',
    textColor: '#292524',
    titleFont: '"Georgia", "Times New Roman", serif',
    bodyFont: '"Inter", "SF Pro Text", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.6)',
    isDark: false,
    categories: ['academic', 'educator']
  },
];
