
import { Theme } from './theme-types';

export const themes: Theme[] = [
  {
    id: 'stardust',
    name: 'Stardust',
    description: 'A sleek dark theme with stellar accents',
    background: 'linear-gradient(135deg, #1A1F2C 0%, #2C3345 100%)',
    accentColor: '#9b87f5',
    textColor: '#FFFFFF',
    titleFont: '"Montserrat", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.1)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'creme',
    name: 'Crème',
    description: 'Soft cream tones for a professional look',
    background: 'linear-gradient(109.6deg, rgba(223,234,247,1) 11.2%, rgba(244,248,252,1) 91.1%)',
    accentColor: '#6E59A5',
    textColor: '#1A1F2C',
    titleFont: '"Playfair Display", serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: '#FFFFFF',
    isDark: false,
    categories: ['consulting', 'academic']
  },
  {
    id: 'vortex',
    name: 'Vortex',
    description: 'Dynamic swirls of blue and purple',
    background: 'linear-gradient(135deg, #0EA5E9 0%, #8B5CF6 100%)',
    accentColor: '#F97316',
    textColor: '#FFFFFF',
    titleFont: '"Montserrat", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.15)',
    isDark: true,
    categories: ['modern']
  },
  {
    id: 'pearl',
    name: 'Pearl',
    description: 'Clean, minimal design with subtle highlights',
    background: '#FFFFFF',
    accentColor: '#0EA5E9',
    textColor: '#333333',
    titleFont: '"Inter", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'linear-gradient(109.6deg, rgba(223,234,247,1) 11.2%, rgba(244,248,252,1) 91.1%)',
    isDark: false,
    categories: ['consulting', 'academic']
  },
  {
    id: 'lux',
    name: 'Lux',
    description: 'Luxurious dark theme with golden accents',
    background: '#222222',
    accentColor: '#FFD700',
    textColor: '#FFFFFF',
    titleFont: '"Playfair Display", serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'linear-gradient(135deg, rgba(255, 215, 0, 0.2) 0%, rgba(255, 215, 0, 0.05) 100%)',
    isDark: true,
    categories: ['dark', 'consulting']
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Earthy green tones inspired by nature',
    background: 'linear-gradient(90deg, hsla(139, 70%, 75%, 1) 0%, hsla(63, 90%, 76%, 1) 100%)',
    accentColor: '#2E7D32',
    textColor: '#333333',
    titleFont: '"Montserrat", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.8)',
    isDark: false,
    categories: ['academic']
  },
  {
    id: 'coral',
    name: 'Coral',
    description: 'Warm coral gradients with a modern feel',
    background: 'linear-gradient(to right, #ee9ca7, #ffdde1)',
    accentColor: '#E91E63',
    textColor: '#333333',
    titleFont: '"Montserrat", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.8)',
    isDark: false,
    categories: ['modern']
  },
  {
    id: 'slate',
    name: 'Slate',
    description: 'Professional slate gray for business presentations',
    background: 'linear-gradient(to right, #243949 0%, #517fa4 100%)',
    accentColor: '#FFC107',
    textColor: '#FFFFFF',
    titleFont: '"Inter", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.1)',
    isDark: true,
    categories: ['dark', 'consulting']
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Ultra-clean design with minimal distractions',
    background: '#F8F9FA',
    accentColor: '#212529',
    textColor: '#212529',
    titleFont: '"Inter", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: '#FFFFFF',
    isDark: false,
    categories: ['consulting', 'academic', 'modern']
  },
  {
    id: 'royal',
    name: 'Royal',
    description: 'Rich purple tones with elegant styling',
    background: 'linear-gradient(102.3deg, rgba(147,39,143,1) 5.9%, rgba(234,172,232,1) 64%, rgba(246,219,245,1) 89%)',
    accentColor: '#FFD700',
    textColor: '#FFFFFF',
    titleFont: '"Playfair Display", serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.15)',
    isDark: true,
    categories: ['dark', 'modern']
  },
  {
    id: 'chalk',
    name: 'Chalk',
    description: 'Chalkboard style for an academic feel',
    background: '#2A3B4C',
    accentColor: '#FFFFFF',
    textColor: '#FFFFFF',
    titleFont: '"Comic Sans MS", cursive',
    bodyFont: '"Comic Sans MS", cursive',
    cardDesign: 'rgba(255, 255, 255, 0.1)',
    isDark: true,
    categories: ['dark', 'academic']
  },
  {
    id: 'sunrise',
    name: 'Sunrise',
    description: 'Warm sunrise colors for an energetic presentation',
    background: 'linear-gradient(90deg, hsla(29, 92%, 70%, 1) 0%, hsla(0, 87%, 73%, 1) 100%)',
    accentColor: '#FF5722',
    textColor: '#333333',
    titleFont: '"Montserrat", sans-serif',
    bodyFont: '"Inter", sans-serif',
    cardDesign: 'rgba(255, 255, 255, 0.8)',
    isDark: false,
    categories: ['modern']
  }
];
