<<<<<<< HEAD
=======

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
>>>>>>> 0586fc0ddfcb662ea18ceb0a567de8e4d6b73122

interface SupabaseResponse<T> {
  data: T | null;
  error: Error | null;
}

<<<<<<< HEAD
export const supabase = {
  from: (table: string) => ({
    insert: (data: any) => ({
      select: () => ({
        single: (): Promise<SupabaseResponse<any>> => {
          console.log(`Inserting into ${table}:`, data);
          return Promise.resolve({
            data: { id: 'mock-id', ...data },
            error: null
          });
        }
      })
    }),
    select: () => ({
      eq: (column: string, value: any) => ({
        single: (): Promise<SupabaseResponse<any>> => {
          console.log(`Selecting from ${table} where ${column} = ${value}`);
          return Promise.resolve({
            data: { id: 'mock-id' },
            error: null
          });
        }
      })
    })
  }),
  functions: {
    invoke: (name: string, { body }: { body: any }): Promise<SupabaseResponse<any>> => {
      console.log(`Invoking function ${name} with body:`, body);
      
      if (name === 'generate-slides') {
        return Promise.resolve({
          data: {
            slides: [
              {
                title: "Introduction",
                bullets: ["Welcome to our presentation", "Today we'll discuss key points", "Questions at the end please"]
              },
              {
                title: "Main Points",
                bullets: ["First important point", "Second critical insight", "Key takeaway"]
              }
            ]
          },
          error: null
        });
      }
      
      return Promise.resolve({
        data: null,
        error: null
      });
    }
  }
};
=======
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
>>>>>>> 0586fc0ddfcb662ea18ceb0a567de8e4d6b73122
