
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const supabaseUrl = 'https://iawgrcdgaqdrdigvoxjx.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhd2dyY2RnYXFkcmRpZ3ZveGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NDkwMDMsImV4cCI6MjA5MTIyNTAwM30.CzpGd1aBxogzCLRbniqltE4O6bHO1XsiQZFDP-yL9Vg'

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey)
